name: Export Unstructured Image
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Image
        run: docker pull downloads.unstructured.io/unstructured-io/unstructured-api:latest
      - name: Save Image to Tar
        run: docker save downloads.unstructured.io/unstructured-io/unstructured-api:latest -o unstructured_api.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unstructured-image-tar
          path: unstructured_api.tar
          retention-days: 1
