- name: Save Image to Tar
        run: docker save downloads.unstructured.io/unstructured-io/unstructured-api:latest -o unstructured.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unstructured-api-package  # 这是下载时的名字
          path: unstructured.tar          # 必须和上面 -o 后面的名字一致
